name: Build and deploy Node.js project to Azure Function App - mcp-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './package'
  NODE_VERSION: '18'  # MCP SDK は Node 22 より 18 のほうが安定する場合あり

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Zip artifact for deployment
        run: |
         cd dist
         zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2AF4E807849D4DA488C128E16B5B4CDB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0E55F7B43C1A413C994C985A0B79EA06 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_793D0F2B72D549BDA3EF3553EF708BDE }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'mcp-test'
          slot-name: 'Production'
          package: './package'
